""" workout name change

Revision ID: 47302de1f9a7
Revises: 042992964cd5
Create Date: 2023-04-27 23:34:54.712326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47302de1f9a7'
down_revision = '042992964cd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workout_name', sa.String(), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('workout_name')

    # ### end Alembic commands ###
